### ISSUE TITLE
Support Rails 7.2

### ISSUE THREAD

**Issue by ekzobrain** [malomalo/activerecord-filter#21]
Now fails with exception:
```
wrong number of arguments (given 2, expected 0..1)
/Users/macbook/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-filter-7.0.0/lib/active_record/filter.rb:435:in `build_arel'
/Users/macbook/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/active_record_extended-3.3.0/lib/active_record_extended/patch/relation_patch.rb:69:in `build_arel'
/Users/macbook/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/relation/query_methods.rb:1573:in `block in arel'
```

**Comment by malomalo** [comment]
It is coming within the next few weeks, maybe sooner.

**Comment by ekzobrain** [comment]
@malomalo I see that this is fixed now. Could you, please, make a release?
